//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Employees_Rus
    {
        public int Employees_Info_ID { get; set; }
        public string Фамилия_сотрудника { get; set; }
        public string Имя_сотрудника { get; set; }
        public string Отчество_сотрудника { get; set; }
        public int Возраст_сотрудника { get; set; }
    }
}
